### ISSUE TITLE
最新yolov5转换缺少aten::clone算子

### ISSUE THREAD

**Issue by wjj19950828** [PaddlePaddle/X2Paddle#896]
感谢您参与 X2Paddle 社区！ 问题模版为了 X2Paddle 能更好的迭代，例如新功能发布、 RoadMaps 和错误跟踪. :smile_cat:

## 问题描述

- 错误信息
- 错误截图

## 具体信息

- 转换模型后用处
    - [x] 使用 Paddle 框架/ PaddleInference 推理预测
    - [ ] 使用 Paddle-Lite 做移动端推理
    - [ ] 转换预训练参数，再使用 Paddle 进行模型开发
- 模型来源
YOLOv5：https://github.com/ultralytics/yolov5

same as https://github.com/PaddlePaddle/Paddle/issues/46146

**Comment by glenn-jocher** [comment]
YOLOv5 export fails due to unsupported torch Tensor `.clone()` operation. Error first reported in https://github.com/ultralytics/yolov5/issues/9439

```bash
PaddlePaddle: starting export with X2Paddle 1.3.8...
[WARNING] PyTorch==1.6.0 is recommended
Now translating model from PyTorch to Paddle.

========= 1 OPs are not supported yet ===========
========== aten::clone ============
PaddlePaddle: export failure ❌ 3.6s: Model is not supported yet.
```

<img width="1154" alt="Screenshot 2022-09-16 at 13 36 39" src="https://user-images.githubusercontent.com/26833433/190630368-5a3723ed-74cf-4483-ac12-15a632ae25e3.png">

### Code to reproduce
```python
!git clone https://github.com/ultralytics/yolov5  # clone
%cd yolov5
%pip install -qr requirements.txt x2paddle paddlepaddle # install

!python export.py --weights yolov5s.pt --include paddle  # export
```

**Comment by wjj19950828** [comment]
fixed in https://github.com/ultralytics/yolov5/pull/9458
